FROM rust:1.74-alpine AS builder
WORKDIR /app
RUN apk add --no-cache pkgconfig openssl-dev
COPY . .
RUN cargo build --release --target aarch64-unknown-linux-gnu --bin nodecook-agent

FROM alpine
WORKDIR /
RUN addgroup --system nodecook || echo "Failed to create group" && adduser --system --group nodecook || echo "Failed to create user"
COPY --from=builder /app/target/aarch64-unknown-linux-gnu/release/nodecook-agent /usr/local/bin/
USER nodecook
CMD ["/usr/local/bin/nodecook-agent"]