FROM rust:1.74 AS chef
USER root
RUN apt-get update && apt-get install -y pkg-config libssl-dev openssl
RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
ARG ARCH=aarch64-unknown-linux-gnu
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release --target ${ARCH} --recipe-path recipe.json
COPY . .
RUN cargo build --release --target ${ARCH} --bin nodecook-agent

FROM debian:buster-slim AS runtime
ARG ARCH=aarch64-unknown-linux-gnu
RUN apt-get update && apt-get install -y libssl-dev openssl
RUN addgroup --system nodecook && adduser --system --group nodecook
COPY --from=builder /app/target/${ARCH}/release/nodecook-agent /usr/local/bin/
USER nodecook
CMD ["/usr/local/bin/nodecook-agent"]